-- Session 1
-- BEGIN;
-- SELECT *
-- FROM pizzeria
-- WHERE name = 'Pizza Hut';
--  id |   name    | rating
-- ----+-----------+--------
--   1 | Pizza Hut |      4
-- (1 row)


-- SELECT *
-- FROM pizzeria
-- WHERE name = 'Pizza Hut';
--  id |   name    | rating
-- ----+-----------+--------
--   1 | Pizza Hut |    3.6
-- (1 row)
-- END;

-- Session 2
-- BEGIN;
-- UPDATE pizzeria
-- SET rating = 3.6
-- WHERE name = 'Pizza Hut';
-- END;
-- SELECT *
-- FROM pizzeria
-- WHERE name = 'Pizza Hut';
--  id |   name    | rating
-- ----+-----------+--------
--   1 | Pizza Hut |    3.6
-- (1 row)